"""Add gender and jurusan fields

Revision ID: 169d5f459cf9
Revises: 922ddb35eaaf
Create Date: 2025-05-15 09:46:16.103020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '169d5f459cf9'
down_revision = '922ddb35eaaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('jurusan', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_column('jurusan')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
