"""Add payment fields

Revision ID: 189c891a737d
Revises: 169d5f459cf9
Create Date: 2025-05-20 07:29:39.296408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189c891a737d'
down_revision = '169d5f459cf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_proof', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_column('payment_status')
        batch_op.drop_column('payment_proof')

    # ### end Alembic commands ###
