"""Add document fields

Revision ID: 922ddb35eaaf
Revises: 10666509789f
Create Date: 2025-05-08 10:47:32.494852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922ddb35eaaf'
down_revision = '10666509789f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('akta_kelahiran', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('kartu_keluarga', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ijazah_smp', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('foto_siswa', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ktp_ortu', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('nisn_doc', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('nilai_rapor', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sertifikat_prestasi', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_column('sertifikat_prestasi')
        batch_op.drop_column('nilai_rapor')
        batch_op.drop_column('nisn_doc')
        batch_op.drop_column('ktp_ortu')
        batch_op.drop_column('foto_siswa')
        batch_op.drop_column('ijazah_smp')
        batch_op.drop_column('kartu_keluarga')
        batch_op.drop_column('akta_kelahiran')

    # ### end Alembic commands ###
